### PR TITLE
Inline sw manifest to avoid weirdness with etags.

### LINKED ISSUE #3879: Site is taking extremely long to load on repeat load
**Describe the bug**
Visit web.dev (assuming you have a preexisting service worker). The site takes a very long time to load and the loading spinner never stops.

Now try opening an incognito window and visiting the site, notice that the site loads almost immediately.

### PR DESCRIPTION
**Pull request by robdodson**
Fixes #3879

Changes proposed in this pull request:

- Inline the sw manifest to avoid etags getting out of sync.

### CODE REVIEW

File: sw-manifest.js [hunk 1]
```diff
@@ -59,20 +60,15 @@ async function buildCacheManifest() {
     config.globPatterns.push('bootstrap.js', 'app.css');
   }
 
-  const toplevelManifest = await getManifest(config);
+  const toplevelManifest = await injectManifest(config);
```
Comment (jeffposnick) [inline sw-manifest.js:63]: You might want to log the `toplevelManifest.count` value somewhere, which is the number of items precached. That was previously being logged, but you remove that message.

The properties available in the return value is documented at https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.injectManifest

**Review by jeffposnick — APPROVED** [review]
The usage seems fine, and when I tested things via `export ELEVENTY_ENV=prod && npm run build`, the correct output was created.

File: sw-manifest.js (hunk 1 above)
Comment (robdodson) [reply sw-manifest.js:63]: added, thanks!
