### PR TITLE
fix(Subscribe): find correct elements in subscribe form, fixes #6663

### LINKED ISSUE #6663: `web-subscribe` element not capturing newsletter subscription on submit
**Describe the bug**
`web-subscribe` element not capturing newsletter subscription on submit when using `{% include 'partials/subscribe-next.njk' %}`

**To Reproduce**
1. Go to `/`
2. Scroll to subscribe form.
3. Click on form and fill out and submit.
4. You get redirected to formbox.

**Expected behavior**
Custom element hijacks experience and doesn't send user to formbox acceptance.

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #6663

Changes proposed in this pull request:

- Finds elements across `subscribe.njk` and `subscribe-next.njk` to attach onto and update.
- Attaches `pages/home.js` to home page
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

File: src/lib/components/Subscribe/index.js [hunk 1]
```diff
@@ -6,6 +6,9 @@ import {BaseElement} from '../BaseElement';
 import {trackError, trackEvent} from '../../analytics';
 import './_styles.scss';
 
+const pTagSelector = 'p.subscribe__error__message';
```
Comment (devnook) [inline src/lib/components/Subscribe/index.js:9]: I think we don't need "p" here since you have a class.

**Review by devnook — APPROVED** [review]
