### PR TITLE
fix(algolia): add landing pages and prioritize them, fixes #4027

### LINKED ISSUE #4027: Landing pages to appear in search for relevant content
**Describe the bug**
For example, "Network reliability" does not appear in search results for "reliability".

**To Reproduce**
Type "reliability" in the site's search box. Results look like this:
image

**Expected behavior**
"Network reliability" appears when I search for "reliable" or "reliability"

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #4027

Changes proposed in this pull request:

- Limit search to just title, description and content. (Things like the URL could have been false positives with the inclusion of "web")
- Add custom ranking sort on new `priority` field.
- Default pages to algolia priority of `1`.
- Set paginated pages algolia priority to `0.9`.
- Set path pages algolia priority to `1.1`.
- Set path pages to use `eleventyComputed` instead of `renderData` for title and what not. (When using `renderData` posts don't have a title, and therefore fail to be indexed by algolia)

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

File: algolia.js [hunk 1]
```diff
@@ -124,7 +124,9 @@ async function index() {
 
   // When indexing data we mark these two fields as fields that can be filtered by.
   await index.setSettings({
+    searchableAttributes: ['title', 'content', 'description'],
```
Comment (devnook) [inline algolia.js:127]: I think we might be using "summary" field on some content

**Comment by devnook** [comment]
This is useful, thanks @MichaelSolati ! Can you please add a description on indexed fields and how to set up algolia priority on the wiki: https://github.com/GoogleChrome/web.dev/wiki/Algolia

**Review by devnook — APPROVED** [review]
