### PR TITLE
fix(BaseResponseElement): scroll to selected option when option is correct, fixes #6463

### LINKED ISSUE #6463: 'Check your understanding' doesn't scroll to correct answer
On [web.dev/learn/forms/form](https://web.dev/learn/forms/form/):

1. Go to ** Check your understanding**.
2. Click on `<form>` (the correct answer).
3. Click **Check** button.

Widget should scroll to the correct answer, but it doesn't. (Ideally, only the correct answer would be displayed.)

Same for other pages that use the same widget.

Also, the **Check** button doesn't render properly once it's clicked (see screenshot below).

image

@beaufortfrancois @rachelandrew @justmarkup fyi

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #6463

Changes proposed in this pull request:

- Add method to scroll to selected, correct, option
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

File: src/lib/components/BaseResponseElement/index.js [hunk 1]
```diff
@@ -172,10 +174,24 @@ export class BaseResponseElement extends BaseElement {
...
   }
 
+  /**
+   * @param {HTMLElement} option HTML ELement to scroll to.
+   */
+  scrollToOption(option) {
+    const {top, height} = option.getBoundingClientRect();
+
+    this.parentElement.scrollTo({
+      top: top - height * 2.5,
```
Comment (devnook) [inline src/lib/components/BaseResponseElement/index.js:184]: Please add comment where this 2.5 number came from.

**Review by devnook — APPROVED** [review]
