### PR TITLE
hide Glitch on codelabs on mobile

### LINKED ISSUE #2344: We should hide Glitch on codelabs on mobile
**Describe the bug**
Currently we still load the Glitch for codelabs on small screens even though it's not visible or usable (<700px).

**To Reproduce**
open e.g., https://web.dev/codelab-remove-unused-code/, make screen small

**Expected behavior**
Something more useful than happens now.

Let's add a blurb saying this is unsupported at the top of the codelab.

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR hides Glitch for codelabs on mobile devices as it's not usable.

Live preview: https://deploy-preview-2389--web-dev-staging.netlify.com/codelab-remove-unused-code/

Fixes #2344

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
1. Do you already have something in mind for the notice?
1. Shall we load conditionally the iframe with media queries listener in javascript?

**Comment by samthor** [comment]
1. I don't have specific text in mind, but even having a place for it would
be great.

2. Yes, that sounds good, since ResizeObserver isn't quite as supported as
we'd like.

**Comment by beaufortfrancois** [comment]
2. Is there another way to not use `865px`, but the scss value in https://github.com/GoogleChrome/web.dev/pull/2389/commits/d987c2fb7204002021295d52aad1510ee93c43bc?

File: src/lib/components/Codelab/index.js [hunk 1]
```diff
@@ -45,8 +45,8 @@ class Codelab extends BaseElement {
   }
 
   get src() {
-    if (!this.glitch) {
-      return;
+    if (!this.glitch || window.matchMedia('(max-width: 865px)').matches) {
```
Comment (samthor) [inline src/lib/components/Codelab/index.js]: I appreciate this but I'd rather have a listener that maintains/updates a property on this element, so we can add or remove the codelab if the user changes the window size.

Comment (beaufortfrancois) [reply src/lib/components/Codelab/index.js]: @samthor WDYT of https://github.com/GoogleChrome/web.dev/pull/2389/commits/e0c08fae0a23ddeb0e84cca66aa68faf1c97c4eb?

Comment (beaufortfrancois) [reply src/lib/components/Codelab/index.js]: @samthor New commit at https://github.com/GoogleChrome/web.dev/pull/2389/commits/84e05226ccde4dc366b3add4e065bc368713b6b6
