### PR TITLE
Don't switch tabs if the user is opening/closing the schedule modal

### LINKED ISSUE #3336: Closing the modal switches the tabs to the current day.
**Describe the bug**
If it's day 3, and you click on the day 1 tab and click on a session and then close the modal, the tabs will switch back to day 3.

**Expected behavior**
I think the user expectation is the tabs would stay on day 1 if they taken an action to switch them to day 1.

### PR DESCRIPTION
**Pull request by robdodson**
Fixes #3336.

Changes proposed in this pull request:

- Adds a wasModalOpen internal flag to EventSchedule to help it know when to reflect the current day in the tabs.

### CODE REVIEW

File: src/lib/components/EventSchedule/index.js [hunk 1]
```diff
@@ -177,15 +178,25 @@ class EventSchedule extends HTMLElement {
...
-    // Don't change the tab for the user if a modal is already open.
-    if (!this._modalElement.open && activeEventDay) {
-      this._tabsElement.activeTab = activeEventDay.index;
+    // If the user has clicked to a different day, opened and closed a modal
+    // then don't do anything.
+    // If this is not the case then it means that either we're loading the
+    // page for the first time, or the user has left the tab open and we're
+    // transitioning to the next day. In that case, update the tabs element
+    // to reflect the current day.
+    if (!this._wasModalOpen) {
```
Comment (MichaelSolati) [inline src/lib/components/EventSchedule/index.js:190]: Can't this all be merged into one `if` satetement?

Comment (robdodson) [reply src/lib/components/EventSchedule/index.js:190]: mmmmm yep. I think so. let me do that.
