### PR TITLE
fix(percy): update percy to use new CLI/SDK, fixes #6943

### LINKED ISSUE #6943: Percy out of date
Percy SDK we use for screenshots is deprecated, we need to upgrade percy => https://docs.percy.io/docs/migrating-to-percy-cli

image

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #6943

Changes proposed in this pull request:

- Install new SDK/CLI
- Update YML
- Update JS script to parse screenshots

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

### CODE REVIEW

File: tools/percy/snapshots.js [hunk 1]
```diff
@@ -1,111 +1,114 @@
...
-  // These flags remove Percy's single-process flag. Without these, any page
-  // with an iframe will crash puppeteer (and percy).
-  {args: ['--no-sandbox', '--disable-setuid-sandbox']},
-);
+  for (const pageToTest of pagesToTest) {
+    const page = await browser.newPage();
+    const url = new URL(pageToTest.url, 'http://localhost:8080').href;
+    await page.goto(url, {waitUntil: 'networkidle0'});
+    await page.evaluate(scrollToBottom);
+    // Wait for the SPA to update the active link in the top nav.
```
Comment (devnook) [inline tools/percy/snapshots.js:107]: We don't do spa atm. Do we still need this?

Comment (MichaelSolati) [reply tools/percy/snapshots.js]: I don't think we do, I'll remove it, and if we end up needing it we could always add it back...

**Review by devnook — APPROVED** [review]
