### PR TITLE
Obfuscate error message

### LINKED ISSUE #5513: web.dev/measure error message leaks API key
**Describe the bug**
The API key used by web.dev/measure is leaked in an error message. (I would recommend it be regenerated once this bug is fixed.)

**To Reproduce**
1. Go to https://web.dev/measure/
2. Look up any URL during an API outage.
3. See API key in error

**Expected behavior**
The error message should not contain Google's internal API key.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by devnook**
Fixes #5513

### CODE REVIEW

**Review by MichaelSolati — APPROVED** [review]

File: src/lib/actions.js [hunk 1]
```diff
@@ -60,10 +60,11 @@ export const requestRunLighthouse = store.action((state, url) => {
   })();
 
   return p.catch((err) => {
-    console.warn('failed to run Lighthouse', url, err);
+    const errMsg = err.name === 'FetchError' ? err.name : err.toString();
+    console.warn('failed to run Lighthouse', url, errMsg);
 
     const update = {
-      lighthouseError: err.toString(),
+      lighthouseError: errMsg,
```
Comment (robdodson) [inline src/lib/actions.js:67]: is lighthouseError every logged? It seems like errMsg still does err.toString() in some instances so I'm not sure I understand how this fixes the issue?

Comment (robdodson) [reply src/lib/actions.js:67]: maybe a better question:

What was causing the issue in the first place? Are only FetchErrors displaying the key or do other kinds of errors?

Comment (devnook) [reply src/lib/actions.js:67]: LighthouseError is actually displayed in the UI. In case of FetchError, it means there was a problem in fetch from Pagespeed API, and the url (including key) of Pagespeed api is included in the error message. This is not the case for other errors which originate from Ligthouse service (and not pagespeed).
