### PR TITLE
fix(meta): remove double quote from text in meta attributes, fixes #2627

### LINKED ISSUE #2627: OGP doesn't pickup double quote
**Describe the bug**
When posting a link on Twitter, quote is stripped form the page title
For example, [`Understanding "same-site" and "same-origin"`](https://web.dev/same-site-same-origin/) is displayed as `Understanding`.
https://twitter.com/agektmr/status/1251404023342587906

This is probably caused by the OGP not being html-escaped.

### PR DESCRIPTION
**Pull request by MichaelSolati**
Fixes #2627

Replaces double quote's in attributes of meta tags using the `strip` function's `additionallyForbidden` argument.

### CODE REVIEW

File: src/site/_filters/strip.js [hunk 1]
```diff
@@ -18,15 +18,15 @@
  * Removes any characters that should not exist in a string.
```
Comment (samthor) [inline src/site/_filters/strip.js:18]: can you update this comment say "for presentation", rather than for any other reason?
