### PR TITLE
make 404s always go to network

### LINKED ISSUE #2488: Service worker can prevent redirects from working
**Describe the bug**
If a post accidentally goes live and we remove it and ship a redirect the service worker will cause the user to see a 404 instead of the redirect.

These are the steps I observed today:

- We accidentally shipped /digging-into-the-privacy-sandbox/
- We moved the post to `_drafts` and add a redirect to `_redirects.yaml`
- If you visit the site in a new incognito window and type https://web.dev/digging-into-the-privacy-sandbox/ into the url bar you'll get the redirect.
- However, if you first visit http://web.dev and then type https://web.dev/digging-into-the-privacy-sandbox/ into the URL bar you'll get a 404.

### PR DESCRIPTION
**Pull request by samthor**
Fixes #2488 and #2529.

This (hopefully...) simplifies our SW a bit by treating 404's as unrecoverable errors that always go to the network. This occurs in the Service Worker as well as in the SPA routing (so a 404 will "break" the SPA). We just don't know if there's really a redirect backing whatever page 404'ed otherwise.

I've also added a comment to the redirects YAML to make it clear that trailing slashes there are unnecessary.

### CODE REVIEW

File: src/lib/sw.js [hunk 1]
```diff
@@ -104,56 +104,19 @@ workboxRouting.registerRoute(
...
-    return redirectResponse;
-  },
-);
-
-/**
- * Match fetches for patials, for SPA requests. Matches "/foo-bar/index.json" and
- * "/foo-bar/many/parts/index.json", for partial SPA requests.
- */
-const partialPathRe = new RegExp('^/([\\w-]+/)*index\\.json$');
+const partialPathRe = new RegExp('^/([\\w-]+/)*\\w+\\.json$');
```
Comment (robdodson) [inline src/lib/sw.js:112]: what happens if the site requests a `.json` file that isn't related to partials. Will this send it to the network?

File: src/site/content/en/_redirects.yaml [hunk 2]
```diff
@@ -1,3 +1,16 @@
...
+#
+#  (1) Simple redirects, e.g., "from: /foo"
+#      - These don't match anything under this URL, like "/foo/bar"
+#      - No trailing slash is required, as this matches "/foo", "/foo/" and
+#        "/foo/index.html"
+#
+#  (2) Group redirects, e.g., "from: /foo/...", which will match the top-level
+#      path (with the same rules as (1)) as well as any descendant paths
+#
+# WARNING! Redirects DO NOT take priority over static content.
```
Comment (robdodson) [inline src/site/content/en/_redirects.yaml:12]: Can you add an example so folks can quickly grok what this means.

Comment (robdodson) [reply src/site/content/en/_redirects.yaml:12]: Like, we're trying to say "If you try to redirect /foo, but there's a file at /foo/index.html, then we're going to still serve /foo/index.html. You have to move the file."

File: src/site/content/en/_redirects.yaml [hunk 3]
```diff
@@ -1,3 +1,16 @@
+# Master redirects file for web.dev. This mirrors the old DevSite file.
+# There are two types of redirects:
+#
+#  (1) Simple redirects, e.g., "from: /foo"
+#      - These don't match anything under this URL, like "/foo/bar"
```
Comment (robdodson) [inline src/site/content/en/_redirects.yaml:5]: Maybe rephrase to something like:

These do not match **subpaths**. i.e., "from: /foo" will match "/foo" and "/foo/" but not "/foo/bar"
