### PR TITLE
fix(toc): set overflow of TOC button to be hidden, fixes #3783

### LINKED ISSUE #3783: Site has horizontal scroll on mobile.
I think this is caused by the ToC. It seems to be pushing the social buttons offscreen on mobile.

### PR DESCRIPTION
**Pull request by MichaelSolati**

### CODE REVIEW

File: src/lib/components/TableOfContents/index.js [hunk 1]
```diff
@@ -98,11 +98,14 @@ class TableOfContents extends BaseStateElement {
     for (const heading of headings) {
       const href = `#${heading.target.getAttribute('id')}`;
       const link = links.find((l) => l.getAttribute('href') === href);
```
Comment (samthor) [inline src/lib/components/TableOfContents/index.js:100]: Unrelated but is it worth converting `links` into an object mapping from href to link, so we can remove this find?

**Review by samthor — APPROVED** [review]

File: src/lib/components/TableOfContents/index.js (hunk 1 above)
Comment (MichaelSolati) [reply src/lib/components/TableOfContents/index.js]: Done, well, I used a Map instead of just making an object as it's easier to iterate through if needed, but it saves the need to use the `find` method.
